[package]
name = "font"
version = "0.1.0"
authors = ["biud436 <biud436@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
encoding_rs = "0.8.23"